package id.ac.poliban.mi.listligainggris;

import java.util.ArrayList;
import java.util.List;

public class LigaInggrisData {
    static List<LigaInggris> getLigaInggrises() {
        List<LigaInggris> data = new ArrayList<>();
            {
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/7/7a/Manchester_United_FC_crest.svg/220px-Manchester_United_FC_crest.svg.png", "Manchester United", "Manchester United Football Club adalah sebuah klub sepak bola profesional Inggris yang berbasis di Old Trafford, Manchester Raya, yang bermain di Liga Inggris. Didirikan sebagai Newton Heath LYR Football Club pada tahun 1878, klub ini berganti nama menjadi Manchester United pada 1902 dan pindah ke Old Trafford pada tahun 1910."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/5/53/Arsenal_FC.svg/180px-Arsenal_FC.svg.png", "Arsenal", "Arsenal Football Club (dikenal pula sebagai Arsenal atau The Gunners) adalah klub sepak bola profesional Inggris yang berbasis di daerah Holloway, London. didirikan pada 1886 dengan nama Dial Square. Klub ini bermain di Liga Utama Inggris yang termasuk salah satu klub tersukses di sepak bola Inggris, yang telah memenangkan 13 gelar kasta utama Liga Inggris (10 pada era Divisi Pertama dan 3 pada era Premier League) dan 13 gelar di Piala FA (Gelar paling banyak). Arsenal memegang rekor untuk periode terpanjang berada di kasta puncak Liga Inggris tanpa pernah terdegradasi sejak musim 1919 dan menjadi tim pada peringkat pertama dalam klasemen Liga Inggris sepanjang abad ke-20.[4] Arsenal menjadi tim kedua di Inggris yang menyelesaikan semusim liga tanpa kalah (musim 2003–04) dan tim pertama yang melakukannya pada era di mana satu musim berlangsung 38 pertandingan."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/f/f9/Aston_Villa_FC_crest_%282016%29.svg/150px-Aston_Villa_FC_crest_%282016%29.svg.png", "Aston Villa", "Aston Villa Football Club (/ˈæstən ˈvɪllə/; juga dikenal sebagai Villa, The Villa, The Villans dan The Lions)[5] adalah klub sepak bola profesional yang bermarkas di Villa Park, Birmingham, Inggris. Klub ini bermain di Liga Utama Inggris dan merupakan salah satu klub pendiri Liga Sepak Bola (Football League) pada tahun 1888 serta Liga Utama pada tahun 1992. Aston Villa merupakan salah satu klub tertua dan tersukses Inggris."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/170px-AFC_Bournemouth_%282013%29.svg.png", "A.F.C. Bournemouth", "A.F.C. Bournemouth merupakan sebuah klub sepak bola profesional asal Inggris yang saat ini bermain di Liga Primer Inggris. Klub ini bermain di Lapangan Dean Court di Kings Park, Boscombe, Bournemouth, Dorset dan sudah ada sejak tahun 1899.\n" +
                        "\n" +
                        "Awalnya klub ini pada saat didirikan pada tahun 1890 bernama Boscombe St. John's Institute FC tetapi dibubarkan pada tahun 1899 dan didirikan ulang pada tahun 1899 dengan nama Boscombe FC.\n" +
                        "\n" +
                        "Klub ini sudah memenangkan tingkatan ke-dua dan ke-tiga Liga Inggris, dan pernah menjadi juara tingkatan ke-empat sebanyak dua kali. Mereka juga pernah memenangkan Liga Selatan Inggris, Trofi Liga Inggris, dan juga Piala Sepak Bola Disisi Ketiga Selatan."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/200px-Brighton_%26_Hove_Albion_logo.svg.png", "Brighton & Hove Albion", "Brighton & Hove Albion Football Club adalah sebuah klub sepak bola profesional asal Inggris yang berbasis di kota pantai Brighton & Hove, di timur Sussex. Sering disebut sebagai Brighton & Hove Albion atau hanya sekadar sebagai Brighton. Saat ini bermain di Football League Championship, tingkat kedua dari sistem liga sepak bola Inggris, menggelar pertandingan di Stadion Falmer berpakasitas 30.750 penonton, yang dikenal dalam tujuan sponsor sebagai Stadion Komunitas American Express, atau singkatnya Amex.. Mereka akan menjalankan debut Liga Utama mereka di musim 2017-18 setelah menyegel promosi otomatis dari Kejuaraan EFL."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/6/6d/Burnley_FC_Logo.svg/175px-Burnley_FC_Logo.svg.png", "Burnley FC", "Burnley Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di Burnley, Lancashire. Klub ini sedang bermain di Liga Utama Inggris, kasta tertinggi sepak bola inggris di musim 2016-17 setelah memenangkan liga peringkat kedua yaitu Liga Championship Inggris di musim sebelumnya. Klub ini memainkan pertandingan kandangnya di stadion Turf Moor yang berkapasitas 22.546 penonton. Seragam mereka adalah berwarna nila, sehingga mereka dijuluki Clarets. Klub ini adalah salah satu anggota penemu English Football League pada tahun 1888."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/c/cc/Chelsea_FC.svg/200px-Chelsea_FC.svg.png", "Chelsea", "Chelsea Football Club /ˈtʃɛlsiː/ adalah sebuah klub sepak bola Inggris yang bermarkas di Fulham, London. Chelsea didirikan pada tahun 1905 dan kini berkompetisi di Liga Utama Inggris.\n" +
                        "\n" +
                        "Kesuksesan pertama Chelsea diraih saat meraih gelar juara liga pada tahun 1955. Beberapa gelar dari berbagai kompetisi juga berhasil diraih pada dekade 1960an, 1970an, 1990an, dan 2000an. Sepanjang sejarah penampilan dalam dunia sepak bola di Inggris dan Eropa, Chelsea telah meraih enam gelar juara Liga Utama Inggris, delapan Piala FA, lima Piala Liga, dua Liga Eropa UEFA, dua Piala Winners UEFA, satu Liga Champions UEFA, dan satu Piala Super UEFA.[3] Dalam dua dekade terakhir merupakan periode terbaik kesuksesan Chelsea dengan meraih lebih dari 30 gelar sejak tahun 1997, termasuk untuk pertama kali meraih gelar ganda, Liga Utama Inggris dan Piala FA pada tahun 2010 serta gelar juara Liga Champions UEFA pada tahun 2012 dan Liga Eropa UEFA pada 2013 dan 2019.[4][5]"));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/b/bf/Crystal_Palace_F.C._logo_%282013%29.png/170px-Crystal_Palace_F.C._logo_%282013%29.png","Crystal Palace", "Crystal Palace Football Club merupakan sebuah tim sepak bola Inggris yang bermarkas di London Borough of Croydon dan didirikan pada tahun 1905. Klub ini memainkan pertandingan kandangnya di Selhurst Park yang berkapasitas 26.309 penonton. Seragam mereka berwarna merah-biru."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/7/7c/Everton_FC_logo.svg/200px-Everton_FC_logo.svg.png", "Everton", "Everton Football Club /ˈɛvərtən/ adalah sebuah klub sepak bola profesional yang bermarkas di Kota Liverpool, Inggris, dan merupakan klub rival dari klub sekota Liverpool. Didirikan pada tahun 1878 dan menjadi salah satu pendiri dari Liga Sepak Bola (Football League) pada tahun 1888 serta Liga Primer pada tahun 1992."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/6/6c/Leicester_FC_Logo.svg/200px-Leicester_FC_Logo.svg.png", "Leicester City", "Leicester City F.C. adalah sebuah tim sepak bola Inggris berbasis di Leicester. Leicester Dikenal juga dengan sebutan The Foxes. Klub ini memainkan pertandingan kandangnya di Stadion King Power yang berkapsitas 32.000 penonton.\n" +
                        "\n" +
                        "Mereka bermain di Liga Premier, setelah promosi sebagai juara Football League Championship di 2013-14, kembali ke papan atas sepak bola Inggris setelah satu dekade dan akhirnya menjadi juara di musim 2015-16, atau dua musim setelah promosi.\n" +
                        "\n" +
                        "Leicester dipastikan keluar sebagai juara untuk kali pertama dalam sejarahnya setelah raihan poinnya tak mampu dikejar Arsenal maupun Tottenham diposisi kedua dan ketiga."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/0/0c/Liverpool_FC.svg/180px-Liverpool_FC.svg.png","Liverpool F.C.", "Liverpool Football Club /ˈlɪvərpuːl/ (dikenal pula sebagai Liverpool atau The Reds) adalah sebuah klub sepak bola asal Inggris yang berbasis di Kota Liverpool. Saat ini Liverpool adalah peserta Liga Utama Inggris. Liverpool juga merupakan juara bertahan Liga Champions UEFA musim 2018-2019"));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/e/eb/Manchester_City_FC_badge.svg/200px-Manchester_City_FC_badge.svg.png", "Manchester City", "Manchester City Football Club (dikenal pula sebagai Man City atau The Citizens) adalah sebuah klub sepak bola profesional dari Inggris yang bermain di Liga Premier Inggris. Klub ini merupakaan klub sekota dengan Manchester United dan bermarkas di Stadion Etihad, Manchester."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/5/56/Newcastle_United_Logo.svg/200px-Newcastle_United_Logo.svg.png", "Newcastle United", "Newcastle United Football Club adalah klub sepak bola profesional Inggris yang berbasis di Newcastle upon Tyne, dan bermain di Liga Utama Inggris, kompetisi tingkat teratas dalam sepak bola Inggris. Newcastle United didirikan pada tahun 1892 sebagai hasil penggabungan Newcastle East End dan Newcastle West End, dan bermain di kandangnya saat ini, St James' Park, sejak saat itu. Stadion tersebut dikembangkan menjadi stadion all-seater pada pertengahan 1990-an dan memiliki kapasitas 52.354."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/8/8c/Norwich_City.svg/150px-Norwich_City.svg.png", "Norwich City", "Norwich City Football Club adalah sebuah klub sepak bola Inggris yang didirikan pada tahun 1902. Bermarkas di Norwich, Norfolk. Norwich pada musim 2006-07 bermain di Liga Championship Inggris. Klub ini memainkan pertandingan kandangnya di Stadion Carrow Road yang berkapasitas 26.164 penonton. Seragam mereka berwarna kuning-hijau, sehingga mereka dijuluki Canaries (Kenari)."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/9/9c/Sheffield_United_FC_logo.svg/175px-Sheffield_United_FC_logo.svg.png", "Sheffield United", "Sheffield United Football Club adalah sebuah tim sepak bola profesional Inggris yang bermarkas di kota Sheffield, Yorkshire Selatan, Inggris. Tim ini dibentuk tahun 1889. Saat ini klub Sheffield United bermain di Football League One, kompetisi tingkat ke-3 dalam sistem liga sepak bola Inggris. Mereka adalah tim olahraga pertama yang menggunakan nama 'United' dan dijuluki The Blades, berkat reputasi kota Sheffield yang mendunia untuk produksi baja. Klub ini memainkan pertandingan kandangnya di Bramall Lane yang berkapasitas 33.000 penonton, stadion utama tertua di dunia dan masih menjadi tempat pertandingan sepak bola."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/c/c9/FC_Southampton.svg/180px-FC_Southampton.svg.png", "Southampton", "Southampton Football Club (berdiri dengan nama St. Mary's YMA) merupakan sebuah tim sepak bola Inggris yang didirikan tahun 1898. Bermarkas di Stadion St Mary's, Southampton, Hampshire, Southampton pada musim 2011-12 bermain di Football League Championship. Southampton juga dikenal sebagai akademi sepak bola Liverpool."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/b/b4/Tottenham_Hotspur.svg/140px-Tottenham_Hotspur.svg.png", "Tottenham Hotspur", "Tottenham Hotspur Football Club /ˈtɒtənəm/,[1][2] adalah klub sepak bola yang berasal dari Tottenham, sebuah daerah yang berada di wilayah utara London. Mereka juga dikenal sebagai Spurs, The Spurs dan Tottenham, sementara penggemar mereka memberi mereka nama the Lilywhites karena seragam tradisional mereka yang berwarna putih."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/e/e2/Watford.svg/170px-Watford.svg.png", "Watford F.C.", "Watford Football Club merupakan tim sepak bola profesional Inggris yang bermarkas di Watford, Hertfordshire, dan bermain di Liga Utama Inggris. Klub ini memainkan pertandingan kandangnya di Stadion Vicarage Road yang berkapasitas 22.200 penonton. Seragam mereka berwarna kuning-merah."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/c/c2/West_Ham_United_FC_logo.svg/200px-West_Ham_United_FC_logo.svg.png", "West Ham United F.C.", "West Ham United Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di London. Sejak 2016, klub ini memainkan pertandingan kandangnya di London Stadium yang berkapasitas 80.000 kursi. Sebelumnya Hammers bermain di Boleyn Ground. Seragam mereka berwarna merah-biru."));
                data.add(new LigaInggris("https://upload.wikimedia.org/wikipedia/id/thumb/f/fc/Wolverhampton_Wanderers.svg/200px-Wolverhampton_Wanderers.svg.png", "Wolverhampton Wanderers", "Wolverhampton Wanderers Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di Wolverhampton, Britania Raya yang bermain di Liga Utama Inggris. Klub ini memainkan pertandingan kandangnya di Stadion Molineux yang berkapasitas 32,050 penonton. Seragam mereka berwarna cokelat-hitam. Mereka dijuluki Wolves."));
            }

            return data;

        }
    }
